### ISSUE TITLE
Docs enhancement

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-fonts#22]
The way we've been using o-fonts with the currently next prototype is just by including a script tag and using the globally defined fonts.  (I think antenna do this too)

It would be really nice if there were better docs to support this use case:-

```css
.title {
  font-family: FinancierDisplay;
}
```

Some kind of listing of the available fonts would be super useful...
