### ISSUE TITLE
"Lighter" BentonSans displaying normal font-weight

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-fonts#25]
The css output for Benton Sans lighter won't trigger a font file download (tested in Chrome):
```scss
@font-face {
  font-family: BentonSans;
  font-weight: lighter; // relative keyword, won't work
  font-style: normal;
  src: url("//build.origami.ft.com/files/o-fonts-assets@0.2.2/bentonsans-lighter.eot");
  // ...
}
@font-face {
  font-family: BentonSans;
  font-weight: normal;
  font-style: normal;
  src: url("//build.origami.ft.com/files/o-fonts-assets@0.2.2/bentonsans-normal.eot");
  // ...
}
p { font-weight: lighter; } // will actually be in normal font weight
```

It looks like font-weight needs to be a number or a keyword, but not a relative keyword (bolder / lighter).

### Expected

It should output:

```scss
@font-face {
  font-family: BentonSans;
  font-weight: 200; // the correct font-weight
  font-style: normal;
  src: url("//build.origami.ft.com/files/o-fonts-assets@0.2.2/bentonsans-lighter.eot");
  // ...
}
```

### Possible workaround

In [guss-webfonts](https://github.com/guardian/guss-webfonts) I used a set of human readable weights that were then transformed by the mixins into the correct font-weight numbers:

```scss
/**
 * Human-readable Font-weights
 */
$guss-font-weights: (
    'thin':       100,
    'light':      200,
    'book':       300,
    'regular':    400,
    'medium':     500,
    'semibold':   600,
    'bold':       700,
    'black':      800,
    'ultrablack': 900
) !default;
```

Which was then readable through this helper:

```scss
/**
 * Machine-readable CSS font-weight.
 *
 * @param {String} $keyword - Human-readable keyword in $guss-font-weights
 *
 * @requires {variable} guss-font-weights
 *
 * @example scss
 * font-weight: guss-font-weight(light);
 *
 * @return {Number} - CSS font-weight
 */
@function guss-font-weight($keyword) {
    @return map-get($guss-font-weights, $keyword);
}
```

Feel free to take this as an inspiration for fixing this issue.
