### ISSUE TITLE
Using different weights of web fonts

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/o-fonts#6]
Currently we're specifying different weights of web fonts by using different `font-family` names for each weight (BentonSans-normal, BentonSans-bold etc).

The benefit of this approach is that it works reliably in all our primary experience browsers (IE8 +), but the downside is that the browser doesn't know they're the same family and so the font-family must be explicitly set in style rules that require a different font weight:

``` css
.o-ft-typography-body {
    font-family: BentonSans-normal;
    font-weight: normal;
}

/* This rule shouldn't really be necessary */
.o-ft-typography-body strong {
    font-family: BentonSans-bold;
    font-weight: bold;
}
```

In this example, if the BentonSans-bold font is not loaded, the text will not appear bold. (see https://github.com/Financial-Times/o-ft-typography/issues/17)

The better way to achieve this is to use the same font-family name in multiple `@font-face` declarations, but with different font-weights set there, see here:
http://stackoverflow.com/questions/2436749/how-to-define-bold-italic-using-font-face

IE8 doesn't properly support this, but will use faux-bold instead of the correct web font. In my opinion this is an acceptably graceful degradation and will result in simpler SASS in all our modules.

Are we happy to go adopt this approach?
